default: &default
  adapter: postgresql
  encoding: unicode
  host: "localhost" # move to env
  username: "postgres" #  move to env
  password: <%= ENV["DBI_PASSWORD"] %>
  port: "5432"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: findeducator_development # move to env

test:
  <<: *default
  database: findeducator_test

production:
  <<: *default