default: &default
  adapter: postgresql
  encoding: unicode
  host: "localhost"
  username: "postgres"
  password: <%= ENV["DBI_PASSWORD"] %>
  port: "5432"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: findeducator_development

test:
  <<: *default
  database: findeducator_test

production:
  <<: *default