default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %> # db
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  port: "5432"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DEV_DB'] %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB'] %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_PROD_DB'] %>
